name: Update Tesla News (daily)

on:
  schedule:
    # 매일 00:30 KST == 15:30 UTC
    - cron: '30 15 * * *'
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm i xml2js@0

      - name: Fetch RSS & build JSON
        run: node scripts/fetchTeslaNews.js

      - name: Commit & push if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: update Tesla news"
            git push
          else
            echo "No changes."
          fi
